export const ingredients = [
  ['tomato','Tomato','vegetables','🍅','tomatoes'],['onion','Onion','vegetables','🧅','red onion'],['garlic','Garlic','vegetables','🧄','garlic cloves'],['ginger','Ginger','vegetables','🫚','fresh ginger'],['capsicum','Capsicum','vegetables','🫑','bell pepper|green pepper'],['potato','Potato','vegetables','🥔','potatoes'],['carrot','Carrot','vegetables','🥕','carrots'],['spinach','Spinach','vegetables','🥬','palak'],['broccoli','Broccoli','vegetables','🥦','brocolli'],['cauliflower','Cauliflower','vegetables','🥦','gobi'],['zucchini','Zucchini','vegetables','','courgette'],['mushroom','Mushroom','vegetables','🍄','mushrooms'],['cabbage','Cabbage','vegetables','🥬',''],['corn','Sweet corn','vegetables','🌽','maize'],['peas','Green peas','vegetables','🫛','matar'],['eggplant','Eggplant','vegetables','🍆','aubergine|brinjal'],['cucumber','Cucumber','vegetables','🥒',''],['beetroot','Beetroot','vegetables',''],['green-beans','Green beans','vegetables','🫛','beans'],['leek','Leek','vegetables',''],
  ['lemon','Lemon','fruits','🍋','lemons'],['lime','Lime','fruits',''],['apple','Apple','fruits','🍎','apples'],['banana','Banana','fruits','🍌','bananas'],['avocado','Avocado','fruits','🥑',''],['mango','Mango','fruits','🥭',''],['pineapple','Pineapple','fruits','🍍',''],['orange','Orange','fruits','🍊',''],['grapes','Grapes','fruits','🍇',''],['berries','Mixed berries','fruits','🫐',''],
  ['chicken','Chicken','meat','🍗','chicken breast'],['mince','Ground meat','meat',''],['bacon','Bacon','meat','🥓',''],['sausage','Sausage','meat',''],['turkey','Turkey','meat',''],['lamb','Lamb','meat',''],['pork','Pork','meat',''],['tofu','Tofu','meat',''],
  ['prawns','Prawns','seafood','🦐','shrimp'],['salmon','Salmon','seafood','🐟',''],['tuna','Tuna','seafood',''],['white-fish','White fish','seafood','🐟','cod'],['squid','Squid','seafood',''],['crab','Crab','seafood','🦀',''],
  ['eggs','Eggs','dairy','🥚','egg'],['milk','Milk','dairy','🥛',''],['butter','Butter','dairy','🧈',''],['yogurt','Yogurt','dairy','','curd'],['cream','Cream','dairy',''],['paneer','Paneer','dairy',''],['mozzarella','Mozzarella','dairy','🧀','cheese'],['parmesan','Parmesan','dairy','🧀',''],['cheddar','Cheddar','dairy','🧀',''],['feta','Feta','dairy','🧀',''],
  ['poha','Poha','grains','','flattened rice|aval'],['semolina','Semolina','grains','','sooji|rava'],['whole-wheat-flour','Whole wheat flour','grains','','atta'],['cooked-rice','Cooked rice','grains','🍚','leftover rice'],['rice','Rice','grains','🍚','basmati rice'],['pasta','Pasta','grains','🍝','spaghetti|penne'],['bread','Bread','grains','🍞','toast'],['tortilla','Tortillas','grains','🌮','wraps'],['noodles','Noodles','grains','🍜',''],['oats','Oats','grains',''],['flour','Flour','grains',''],['quinoa','Quinoa','grains',''],['couscous','Couscous','grains',''],['breadcrumbs','Breadcrumbs','grains',''],
  ['moong-dal','Moong dal','legumes','','split mung|yellow dal'],['urad-dal','Urad dal','legumes','','black gram'],['chana-dal','Chana dal','legumes','','split chickpeas'],['split-peas','Split peas','legumes',''],['chickpeas','Cooked chickpeas','legumes','🫛','garbanzo'],['lentils','Lentils','legumes','','dal'],['black-beans','Black beans','legumes','','beans'],['kidney-beans','Cooked kidney beans','legumes','','rajma'],['red-lentils','Red lentils','legumes','','masoor'],['edamame','Edamame','legumes',''],['peanuts','Peanuts','legumes','🥜',''],['cashews','Cashews','legumes',''],
  ['coriander-powder','Coriander powder','spices','','dhania powder|ground coriander'],['rajma-masala','Rajma masala','spices',''],['chaat-masala','Chaat masala','spices',''],['mustard-seeds','Mustard seeds','spices','','rai'],['curry-leaves','Curry leaves','spices','🌿',''],['green-chilli','Green chilli','vegetables','🌶️','chili'],['dried-chilli','Dried red chilli','spices','🌶️',''],['asafoetida','Asafoetida','spices','','hing'],['mint','Mint','spices','🌿',''],['tahini','Tahini','sauces','','sesame paste'],['cumin','Cumin','spices','','jeera'],['turmeric','Turmeric','spices',''],['chilli-powder','Red chilli powder','spices','🌶️','chili powder'],['paprika','Paprika','spices',''],['oregano','Oregano','spices',''],['basil','Basil','spices','🌿','fresh basil'],['coriander','Fresh coriander','spices','🌿','cilantro'],['parsley','Parsley','spices','🌿',''],['rosemary','Rosemary','spices','🌿',''],['thyme','Thyme','spices','🌿',''],['cinnamon','Cinnamon','spices',''],['garam-masala','Garam masala','spices',''],['curry-powder','Curry powder','spices',''],['sesame-seeds','Sesame seeds','spices',''],
  ['neutral-oil','Cooking oil','oils','', 'vegetable oil|cooking oil'],['olive-oil','Olive oil','oils','🫒',''],['sesame-oil','Sesame oil','oils',''],['coconut-oil','Coconut oil','oils','🥥',''],['ghee','Ghee','oils',''],['salt','Salt','oils',''],['black-pepper','Black pepper','oils',''],['water','Water','oils','💧',''],
  ['soy-sauce','Soy sauce','sauces','', 'soya sauce'],['tomato-paste','Tomato paste','sauces',''],['coconut-milk','Coconut milk','sauces','🥥',''],['stock','Stock','sauces',''],['hot-sauce','Hot sauce','sauces','🌶️',''],['ketchup','Ketchup','sauces',''],['mustard','Mustard','sauces',''],['mayo','Mayonnaise','sauces',''],['vinegar','Vinegar','sauces',''],['honey','Honey','sauces','🍯',''],
  ['baking-soda','Baking soda','other',''],['buttermilk','Buttermilk','dairy','','chaas'],['vanilla','Vanilla extract','other',''],['cloves','Cloves','spices','','laung'],['cardamom','Cardamom','spices','','elaichi'],['mirin','Mirin','sauces',''],['rice-noodles','Rice noodles','grains','','pad thai noodles'],['fish-sauce','Fish sauce','sauces',''],['tamarind-paste','Tamarind paste','sauces','','imli'],['spring-onion','Spring onion','vegetables','','scallion'],['bean-sprouts','Bean sprouts','vegetables',''],['gochujang','Gochujang','sauces','','Korean chilli paste'],['peanut-butter','Peanut butter','other',''],['sugar','Sugar','other',''],['baking-powder','Baking powder','other',''],['canned-tomatoes','Canned tomatoes','other',''],['tomato-sauce','Tomato sauce','other',''],['coconut','Desiccated coconut','other','🥥',''],['frozen-veg','Frozen vegetables','other',''],['pickles','Pickles','other',''],['nuts','Mixed nuts','other','🥜','']
].map(([id,name,category,emoji,aliases='']) => ({id,name,category,emoji,aliases:aliases.split('|').filter(Boolean)}));

export const categories = [
  ['all','All ingredients'],['vegetables','Vegetables'],['fruits','Fruit'],['meat','Meat & poultry'],['seafood','Seafood'],['dairy','Eggs & dairy'],['grains','Grains & staples'],['legumes','Lentils & legumes'],['spices','Spices & herbs'],['oils','Oils & fats'],['sauces','Sauces'],['other','Pantry & other']
];
export const cuisines = [['indian','Indian','🍛'],['chinese','Chinese','🥡'],['italian','Italian','🍝'],['mexican','Mexican','🌮'],['thai','Thai','🍜'],['japanese','Japanese','🍱'],['korean','Korean','🥢'],['mediterranean','Mediterranean','🫒'],['middle-eastern','Middle Eastern','🧆'],['american','American','🍔'],['healthy','Healthy-ish','🥗'],['surprise','Surprise me','✨']];
export const byId = Object.fromEntries(ingredients.map(x => [x.id,x]));
